name: atramin
description: Atramin - Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.4.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  material_color_utilities: ^0.13.0
  page_transition: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon/icon.png"
  adaptive_icons_background: "#42BFDD"
  adaptive_icons_foreground: "assets/images/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/e/
    - assets/images/notes/
    - assets/images/splash/
    - assets/images/icon/

  fonts:
    - family: yekan
      fonts:
        - asset: assets/fonts/BYekan+.ttf
    - family: laleh
      fonts:
        - asset: assets/fonts/Lalezar-Regular.ttf